### ISSUE TITLE
Places with double names not searchable. Eg. Trosa-Vagnhärad, Gåsinge-Dillnäs.

### ISSUE THREAD

**Issue by siskahumlesjo** [gu-gridh/shfa-frontend#33]
Places with double names not searchable. Eg. Trosa-Vagnhärad, Gåsinge-Dillnäs.

**Comment by TristanBridge** [comment]
Need backend support

**Comment by ashely-ra** [comment]
Not sure what the issue was?  It seems to work fine in the current version
